config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :sessions
  resources :users
  resources :users
  resources :users
  get '/calendar' => 'calendar#index'
  get '/aboutUs' => 'welcome#aboutUs'
  get '/welcome' => 'welcome#index'
 get '/location' => 'welcome#location'

  root 'welcome#index'

  get '/signup'  => 'users#new'

  get 'admin' => 'users#admin'
  get 'edit'  => 'users#edit'

  resources :users
  resources :posts

  get 'login', :to => 'sessions#new'
  post 'login', :to => 'sessions#create'
  get 'logout', :to => 'sessions#logout'

  get '/post' => 'posts#index'
  get '/posts/new', to: redirect('/posts')
  post 'post' => 'posts#create'
  match '/post/new' => 'posts#new', :via => :post

  resources :users, defaults: { format: 'html' }, only: [:new, :create, :edit, :update, :index, :destroy] do
      member do
        get :profile
        get :settings
      end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :posts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # layout false

  before_action :require_user, :require_admin, only: [:admin, :destroy]
  before_action :require_admin,     only: :destroy
  skip_before_filter :verify_authenticity_token, :only => :destroy

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Job App!"
      session[:user_id] = @user.id
      redirect_to '/'
    else
      flash[:notice] = "Form is invalid"
      redirect_to '/signup'
    end
  end

  def admin
    @user = User.all
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Edit updated"
      redirect_to '/admin'
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/'
  end


  # # GET /users/:id/profile
  # def profile
  #   if (session[:user_id].to_s != params[:id])
  #     redirect_to(:controller => 'users', :action => 'profile', :id => session[:user_id])
  #   else
  #     render "profile"
  #   end
  # end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin.html.erb
<!DOCTYPE html>
<html>


<head>
  <title>Admin panel</title>
  <%= stylesheet_link_tag('admin', :media=>'all')%>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
</head>

<body>


<div class="row">

    <div class="side-menu">

    <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <div class="brand-wrapper">
          <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Brand -->
            <div class="brand-name-wrapper">
                <a class="navbar-brand" style="font-size:40px;margin-top:10px;margin-bottom:10px;" href="/admin">
                     Admin Panel
                </a>
            </div>

        </div>

    </div>
    <div class="side-menu-container">
        <ul class="nav navbar-nav">
            <li class="active"><a href="#"><span class="glyphicon glyphicon-user"></span> User Database</a></li>
            <li><a href="/"><span class="glyphicon glyphicon-home"></span> Home</a></li>
          </ul>
        </div>
  </nav>
  </div>


<div class="container-fluid">
<div class="side-body"><br><br>
  <table id="indextable">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
    <% @user.each do |f| %>
      <tr>
        <td><%= f.first_name %></td>
        <td><%= f.last_name %></td>
        <td><%= f.email %></td>
        <td style="width:20px; padding:0px"><%= link_to 'Edit', edit_user_path(f), class: "linkbtn" %></td> <!--edit later-->
        <td style="width:20px; padding:0px"><%= link_to 'Delete', f, method: :delete, data: { confirm: 'Are you sure?' }, class: "linkbtn" %></td>
      </tr>
    <% end %>
  </table>
</div>
</div>
</div>

  <br>
  <hr>

  <br>

</body>

</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head><title>Edit User</title>
  <%= stylesheet_link_tag('users', :media=>'all')%>
</head>



<body>

 <div id="form">
    <h1>Update your profile</h1>
    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" ,id: "first_name" %><br>
      <%= f.text_field :last_name, :placeholder => "Last name", id: "last_name" %><br>
      <%= f.email_field :email, :placeholder => "Email" ,id: "email_field" %><br>
      <%= f.password_field :password, :placeholder => "Password" ,id: "Password_field" %><br>

      <%= f.submit "Save changes",class: "btn-submit" ,id: "submit_button" %>
    <% end %>

</div>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head><title>Login</title>
  <%= stylesheet_link_tag('users', :media=>'all')%>
</head>

<body>

 <div id="form">
    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" ,id: "first_name" %><br>
      <%= f.text_field :last_name, :placeholder => "Last name", id: "last_name" %><br>
      <%= f.email_field :email, :placeholder => "Email" ,id: "email_field" %><br>
      <%= f.password_field :password, :placeholder => "Password" ,id: "Password_field" %><br>
      <%= f.submit "Create my account", class: "btn-submit" ,id: "submit_button" %>
    <% end %>

  </div>
</body>
</html>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Hello <%= @current_user[:name] %></p>
<% if (@current_user[:admin]) %>
  <%= link_to 'Index', users_path %> |
<% end %>
<%= link_to 'Logout', sessions_logout_path %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head><title>Profile</title>

</head>

<body>

<%= @user.first_name %>, <%= @user.last_name %>,<%= @user.email %>

<style>
</style>

</body>
</html>