config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :sessions
  resources :users
  resources :users
  resources :users
  get '/calendar' => 'calendar#index'
  get '/aboutUs' => 'welcome#aboutUs'
  get '/welcome' => 'welcome#index'
 get '/location' => 'welcome#location'

  root 'welcome#index'

  get '/signup'  => 'users#new'

  get 'admin' => 'users#admin'
  get 'edit'  => 'users#edit'

  resources :users
  resources :posts

  get 'login', :to => 'sessions#new'
  post 'login', :to => 'sessions#create'
  get 'logout', :to => 'sessions#logout'

  get '/post' => 'posts#index'
  get '/posts/new', to: redirect('/posts')
  post 'post' => 'posts#create'
  match '/post/new' => 'posts#new', :via => :post

  resources :users, defaults: { format: 'html' }, only: [:new, :create, :edit, :update, :index, :destroy] do
      member do
        get :profile
        get :settings
      end
    end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  def self.search(search)
    where("job_title ILIKE ? OR company ILIKE ? OR location ILIKE ?", "%#{search}%","%#{search}%","%#{search}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController



  before_action :require_user
	before_action :find_post, only: [:show, :edit, :update, :destroy]

  layout 'post'


  # GET /posts
  # GET /posts.json
  def index
    @search = Post.ransack(params[:q])
    @posts = @search.result
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new


    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    # @post = current_user.post.build(post_params)
    @post = current_user.posts.build(post_params)

		if @post.save
			redirect_to '/post', notice: "Post Added!"
		else
      @errors = @post.errors.full_messages
			render 'new'
		end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
			redirect_to post_path
		else
			render 'edit'
		end

  end


#take user input (search keyword)
def postSearch
  job_title = params[:job_title]
  company = params[:company]
  company = "*"   if params[:company].blank?
  location = params[:location]
  location = "*"   if params[:course_number].blank?
  return  job_title , company, location
end

# # concatenate course name and number to the API url
# def construct_search_URL
#   year, term, name, number = courseSearch
#   url = "http://www.sfu.ca/bin/wcm/course-outlines?" + year + "/" + term + "/" + name + "/" + number
#   return url
# end

# # with concatenated url, retrieve results
# # return array of Hashes
# def getCourseSearchResult
#   returnArray = []
#   obj = parse(getSummary(construct_search_URL))
#   for i in obj
#     returnHash = Hash.new
#     returnArray.push(returnHash)
#     returnHash["Title"] = i["title"]
#     returnHash["Section"] = i["text"]
#   end
#   return returnArray
# end


  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
  #  post = current_user.post.find(params[:id])
    @post.destroy
    # respond_to do |format|
    #   format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    redirect_to '/posts'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_post
    #   @post = Post.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:job_title, :company, :location, :your_name, :phone, :description, :salary, :type)
    end

    def find_post
			@post = Post.find(params[:id])
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="edit_comment">
	<h1 id="editcomment">Edit Posts</h1>
<%= simple_form_for @post do |f| %>
<%= f.input :job_title, label: "Job Title" %>
<%= f.input :company, label: "company" %>
<%= f.input :location, label: "location" %>
<%= f.input :your_name, label: "your_name" %>
<%= f.input :phone, label: "phone" %>
<%= f.input :description, class: "title"%>
<%= f.input :salary, class: "title"%>
<%= f.input :job_type, class: "title"%>
<%= f.button :submit%>
<% end %>
</div>

app/views/posts/index.html.erb
<style>
div.search {
    padding-top: 30px;
    padding-left: 10px;
    float: left;
    height: 700px;
    margin-right: 10px;
    width: 215px;
    border: 1px solid;
}

div.result {
    padding-top: 30px;
    height: 700px;
    width: 500px;
    overflow: hidden;
    border: 1px solid;
}
</style>


<body>
  <div class="search">
    <h3>Advanced Search</h3>
    <%= search_form_for @search do |f| %>
    <div class="field">
      <%= f.label :job_title_cont, "Keywords" %>
      <%= f.text_field :job_title_cont %>
    </div>
    <div class="field">
      <%= f.label :company_cont, "Company" %>
      <%= f.text_field :company_cont %>
    </div>
    <div class="field">
      <%= f.label :location_cont, "Location" %>
      <%= f.text_field :location_cont %><br /><br />
      <iframe
        width="195px"
        height="195px"
        frameborder="0"
        style="border:0;left:0;right:0;bottom:0;top:150px;"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAv7LUS6dItcwF0FayMC4DRh6nfIW6RBt0&q=Vancouver"
         >
      </iframe>
    </div>
    <div class="field">
      <label>Salary</label> <br/>
      <%= f.label :salary_gteq, "Min: " %>
      <%= f.text_field :salary_gteq, style: 'width: 50px;' %>
      <%= f.label :salary_lteq, " ~ Max: " %>
      <%= f.text_field :salary_lteq, style: 'width: 50px;' %>
    </div>
    <div class="actions"> <%= f.submit "Search" %> </div>
    <% end %>

  </div>
  <div class="result">
      <% if @posts.blank? %>
        <h1 style="text-align: center;"> Search Results </h1>
        <h3 style="text-align: center;"> No Results Found </h3>
        <h5 style="text-align: center;"> <label><%= params[:search]%></label><%=render text: " did not match."%> </h5>
        <p style="text-align: center;">Please refine search and try again.</p>
      <% end %>

      <% @posts.each do |post| %>
      	<div class="col-md-4">
      		<div class="message">
      			<h2 class="message-title"><%= post.job_title %></h2>
            <h2 class="message-title"><%= post.company %></h2>
      			<%= link_to "show", post, class: "btn-custom" %>
      		</div>
      	</div>
      <% end %>
      <br>
  </div>
</body>

app/views/posts/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="new_message">
	<h1 class="new-msg-header">Post new jobs</h1>
<%= simple_form_for @post do |f| %>
	<%= f.input :job_title, label: "Job Title", class: "title"  %>
  <%= f.input :company, class: "title"  %>
  <%= f.input :location, class: "title"  %>
  <%= f.input :your_name,  class: "title"  %>
  <%= f.input :phone,  class: "title" %>
	<%= f.input :description, class: "title"%>
	<%= f.input :salary, class: "title"%>
	<%= f.input :job_type, class: "title"%>
	<%= f.button :submit, class: "submit_btn" %>
<% end %>
</div>

</div>

app/views/posts/searchpost.html.erb
<!-- <% #Diaplays search results with course title, number,  and section %> 

<% results = getPostSearchResult %>
<% courseParams = courseSearch %>


<br><br>

<h3 style="margin-left:auto;margin-right:auto; width:65%;"><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Course Search Results </h3>
<div class ="well well-lg" style ="width:65%;margin-left:auto;margin-right:auto;">

<% #redirect to courses page when result is empty. %>
<% #result is empty when user put invalid input/ no input %>
<% if results.empty? %>
  <h4>Please Enter valid Entries. Redirecting...</h4>
  <script type="text/javascript">
    window.setTimeout(function(){window.location.href="/courses"},3000)
  </script>
<% end %>

<% #display course title and section %>
<table id="mycoursetable">
  <% results.each do |result| %>
    <tr>
      <td>
        <strong> <%= result['Title'] %> <%= result['Section'] %> </strong>

        <% #pass course info to /new page to display details %>
        <%= form_tag('/courses/new', :method => 'post') do %>
          <%=hidden_field_tag 'course_year', courseParams[0]  %>
          <%=hidden_field_tag 'course_term', courseParams[1] %>
          <%=hidden_field_tag 'course_name', courseParams[2] %>
          <%=hidden_field_tag 'course_number', courseParams[3] %>
          <%=hidden_field_tag 'course_section', result['Section'] %>
          <div><%= submit_tag 'Details', id: "coursesearchdetails" %></div>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

</div> -->

app/views/posts/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<!-- <h2><%= @post.job_title %></h2> -->
		<p class="message-desc">Job: <%= @post.job_title %><br/>
			 Company: <%= (@post.company)%><br/> Location: <%= (@post.location) %><br/></p>
    <p class="message-desc"> Name: <%= @post.your_name %> <br/>  Phone number:<%= (@post.phone) %><br/></p>
		<br/><p class="message-desc", style= "word-wrap: break-word;"> Description: <br/> <%= @post.description %> <br /><br/></p>
		<br/><p = > Salary: $<%= @post.salary %></p>
		<p class="message-desc"> Job Type: <%=@post.job_type%> </p>

		<hr>


		 <div class="links btn-group">
			<%= link_to "Back", '/posts.1', class: "btn btn-default" %>
			<%= link_to 'Search company location', new_location_path,class: "btn btn-default" ,style:"margin-left:50px;" %>

              <% if current_user.id == @post.user_id %>
				<%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
				<%= link_to "Delete",  post_path(@post),method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
		     <% end %>
		</div>
	</div>
	</div>