config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :sessions
  resources :users
  resources :users
  resources :users
  get '/calendar' => 'calendar#index'
  get '/aboutUs' => 'welcome#aboutUs'
  get '/welcome' => 'welcome#index'
 get '/location' => 'welcome#location'

  root 'welcome#index'

  get '/signup'  => 'users#new'

  get 'admin' => 'users#admin'
  get 'edit'  => 'users#edit'

  resources :users
  resources :posts

  get 'login', :to => 'sessions#new'
  post 'login', :to => 'sessions#create'
  get 'logout', :to => 'sessions#logout'

  get '/post' => 'posts#index'
  get '/posts/new', to: redirect('/posts')
  post 'post' => 'posts#create'
  match '/post/new' => 'posts#new', :via => :post

  resources :users, defaults: { format: 'html' }, only: [:new, :create, :edit, :update, :index, :destroy] do
      member do
        get :profile
        get :settings
      end
    end

end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/concerns/location_controller.rb
class LocationController < ApplicationController
  layout false
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < InheritedResources::Base

  private

    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
    
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
  <%= f.error_notification %>

<div class="newone" style="margin-left :150px; font-color:#000000">
    <%= f.label :Company_Address,style:"width:100%;",require: true %><br />

    <%= f.text_field :address %>


  </div>

  <div class="actions" style="margin-left :150px; font-color:#000000">
      <%= f.label :Latitude_Optional,style:"width:100%;" %><br />
      <%= f.text_field :latitude %>
  </div>

    <div class="actions" style="margin-left :150px; font-color:#000000">

    <%= f.label :Longitude_Optional,style:"width:100%;" %><br />
    <%= f.text_field :longitude %>
  </div>



  <div class="actions" style="margin-left :150px; font-color:#000000">
    <%= f.submit "Search" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Top Searched Company List</h1>
<table>
  <thead>
    <tr>
      <th>Company Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= link_to 'View In Map', location %></td>
            </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Search New Company Location', new_location_path,class: "btn btn-default", style:"margin-left:800px;" %>

app/views/locations/new.html.erb
<h1>Search Company Location</h1>

<%= render 'form' %>


<div class="actions" style="margin-left :150px; font-color:#000000">
<%= link_to 'Top Searched Company List', locations_path,class: "btn btn-default", style:'margin-top:30px;' %>
</div>

app/views/locations/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<div>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

</div>

<%= link_to 'Top Searched Company List', locations_path,class: "btn btn-default", style:'margin-top:30px;' %>