config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :sessions
  resources :users
  resources :users
  resources :users
  get '/calendar' => 'calendar#index'
  get '/aboutUs' => 'welcome#aboutUs'
  get '/welcome' => 'welcome#index'
 get '/location' => 'welcome#location'

  root 'welcome#index'

  get '/signup'  => 'users#new'

  get 'admin' => 'users#admin'
  get 'edit'  => 'users#edit'

  resources :users
  resources :posts

  get 'login', :to => 'sessions#new'
  post 'login', :to => 'sessions#create'
  get 'logout', :to => 'sessions#logout'

  get '/post' => 'posts#index'
  get '/posts/new', to: redirect('/posts')
  post 'post' => 'posts#create'
  match '/post/new' => 'posts#new', :via => :post

  resources :users, defaults: { format: 'html' }, only: [:new, :create, :edit, :update, :index, :destroy] do
      member do
        get :profile
        get :settings
      end
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="application.css" type="text/css" />
  <title>Job Engine</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<style>
    body {
        background-color: # FFFFFF;
    }
    .my-navbar {
        /*margin-bottom: 0px;*/
    }
    .my-panel {
        width: 400px;
        min-height: 400px;
        margin: 100px auto;
        text-align: center;
    }
    .my-panel .logo {
        margin: 10px auto;
        width: 128px;
    }
    .my-panel .form {
        width: 256px;
        margin: 0 auto;
    }
    .my-panel input[type="text"], input[type="password"]  {
        border-radius: 3px;
        border: none;
        color: #333333;
        font-size: 16px;
        height: 46px;
        margin-bottom: 5px;
        padding: 13px 12px;
        width: 100%;
    }
    .btn-login {
        background-color: #00BBFF;
        border-color: #00BBFF;
        border-width: 0;
        color: #FFFFFF;
        display: block;
        margin: 0 auto;
        padding: 15px 50px;
        text-transform: uppercase;
        width: 100%;
    }
</style>
<body>
<nav class="navbar navbar-light bg-light static-top">
 <div class="container">
      <a href="/"> <p class="navbar-brand" style="color: #337ab7">JOB ENGINE</p></a>

      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-right">
          <% if current_user %>
          <div class="dropdown">
            <button class="btn btn-primary">My account</button>
                            <div class="dropdown-content">

          <%= link_to 'Edit profile', edit_user_path(@current_user.id)  %>
          <%= link_to "Logout",logout_path %>
        </div>
  </div>
          <% else %>
            <li>
               <div class="dropdown">
                 <button class="btn btn-primary">Login</button>
                                 <div class="dropdown-content">
                                  <%= link_to "Sign up", 'signup' %>
                                  <%= link_to "Login", 'login' %>
                                 </div>
                </div>
              </li>
          <% end %>
        </li>
      </ul>



  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/layouts/maps.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maps</title>
  <%= stylesheet_link_tag    'maps', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'home', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="stylesheets/aboutUs.css" rel="stylesheet">
</head>
<body>

<nav >
  <div >
    <div >

     <header class="masthead text-white text-center">

      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 style="color: white">Location</h1>
            <p class="lead mb-0" style="color: white">where is the company?</p>
          </div>
          

          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">

              </div>
            </form>
          </div>
        </div>
      </div>
    </header>
    <br>
  <nav>
  <ul class="pagination pagination-lg">
    <li><a href="/maps/burnaby">Job Engine-SFU</a></li>
    
  </ul>
</nav>
    
    </div>
  </div>
</nav>
  <iframe
  width="100%"
  height="400px"
  frameborder="0" 
  style="border:0;left:0;right:0;bottom:0;top:150px;"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAv7LUS6dItcwF0FayMC4DRh6nfIW6RBt0&q=Simon+Fraser+University"
  allowfullscreen >
</iframe>
 

<div id="footer">
  <h3 style="margin-left:5px;"><span class="glyphicon glyphicon-search"></span> Search</h3>
<input type="text" disabled="disabled" class="form-control" style="width:92%;margin-left:15px; float:left;" placeholder="Enter Location">
<button type="submit" disabled="disabled"  style="overflow:hidden; margin-left:5px; margin-right: 5px;" class="btn btn-primary">Go</button>
<br>
<br><br><br>

<hr>
<a href="/welcome"><button type="button" class="btn btn-lg btn-primary">Home</button></a>

</div>
</body>
</html>

app/views/layouts/post.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Posts</title>
  <%= stylesheet_link_tag    'custom', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts">Posts</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active" style="position:absolute;top:15px;"><%= link_to "crete new post", '/posts/new'%> <span class="sr-only">(current)</span></a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">

            <a href="/"><button type="button" class="btn btn-default navbar-btn">Home</button></a>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>


<%= yield %>



</body>
</html>